// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPh00Y1mwO17xFlRm2Ep1UHP2v52uBXCs',
    appId: '1:753074654505:web:278bc2d1d0cfe3e6623b38',
    messagingSenderId: '753074654505',
    projectId: 'flutterdb-249a7',
    authDomain: 'flutterdb-249a7.firebaseapp.com',
    storageBucket: 'flutterdb-249a7.appspot.com',
    measurementId: 'G-D80WD45RR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXisdsOHco1Wx11KrtiOwij6Rn2kJx0qs',
    appId: '1:753074654505:android:9036636c5607f134623b38',
    messagingSenderId: '753074654505',
    projectId: 'flutterdb-249a7',
    storageBucket: 'flutterdb-249a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-lEz7u6v7mcY_OlUclaS6UeSbvoMUotE',
    appId: '1:753074654505:ios:abaed5319cb8085a623b38',
    messagingSenderId: '753074654505',
    projectId: 'flutterdb-249a7',
    storageBucket: 'flutterdb-249a7.appspot.com',
    iosClientId: '753074654505-5n9j304ch5s1rqt4qncfjpg6aul3udn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-lEz7u6v7mcY_OlUclaS6UeSbvoMUotE',
    appId: '1:753074654505:ios:abaed5319cb8085a623b38',
    messagingSenderId: '753074654505',
    projectId: 'flutterdb-249a7',
    storageBucket: 'flutterdb-249a7.appspot.com',
    iosClientId: '753074654505-5n9j304ch5s1rqt4qncfjpg6aul3udn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
